# kodi portable v0.05 config
###################################
$KInstallDir=kodi.app
$KCodename=Nexus
$KInstall=1
$KVer=20.2
$KArchitecture=64

# Installer versions
###################################
$_DownloadBaseUrl=http://mirrors.kodi.tv/releases/windows/
$_Omega=21.1,21.0
$_Nexus=20.2,20.1,20.0
$_Matrix=19.5 19.4 19.3 19.2 19.0
$_Leia=18.9 18.8 18.7
